### ISSUE TITLE
is boxed's intended use case React SSR?

### ISSUE THREAD

**Issue by faceyspacey** [theKashey/kashe#1]
I have a gut feeling this is gold, but I need help figuring out what's going on. 

It seems `boxed` has potential for more caches hits across multiple requests in a React SSR setup. Am I projecting what I'm looking for (out of my own wishful thinking), or is this the intended use case?  

From what I understand WeakMap's have potential to keep its value around in memory until they are garbage collected. It's a useful automation. Is the goal to allow for *multiple cache hits* in the same request by storing *more than one result per selector*? And then when the request is over, all is destroyed???

Or is the goal to hit the cache across requests??

How can `kashe` best help with these goals? Is either use case (cache hits across requests, or more hits for a single request) even its intended use?

Truthfully, I don't understand what you mean by *nested memoization*? Please help me see the light.

**Comment by faceyspacey** [comment]
> boxed is just storing result in a first argument. If cache is not found it is still possible to discover it in a nested cache.
```js
// state1 !== state2. memoization would fail, but memoizedSelector would return the same values
boxedSelector(state1, data) ===   boxedSelector(state2, data)
```

where is the 2nd cache? attached to `bozedSelector` itself like in `memoizedSelector`? What rules decide when to use the `cache` argument versus the one attached to the original selector? Basically, I think im still trying to understand the difference between `boxed` and `inboxed`, and perhaps the algorithm connecting your "hierarchical/nested cache".

**Comment by theKashey** [comment]
> where is the 2nd cache?
```js
const memoizedSelector = kashe(selector);
const boxedSelector = boxed(memoizedSelector); <<-- mistake in a readme :)
boxedSelector(state1, data)
```
So first it would try to find cache in `state1`, then pass call down to `memoizedSelector`, which would try to find cache inside `data`. So it - increases chances to memoization.

```js boxedSelector(state1, data) ===   boxedSelector(state2, data)``` cos result is read from `memoizedSelector`

`inboxed` __replaces cache for all nested calls__, so
```js inboxedSelector(state1, data) !== inboxedSelector(state2, data)``` cos `memoizedSelector ` for left and right calls would use __different weak maps__.

So - it decreases chances to memoization, and once first argument is gone - everything is gone.

**Comment by theKashey** [comment]
See tests :) - https://github.com/theKashey/kashe/blob/master/__tests__/index.tsx#L56

**Comment by faceyspacey** [comment]
I think I get it. The different options (plain kache, boxed, inboxed) are kind of like **tic tack toe**

...each level powered by garbage collected multi-item caches (thanks to weakmaps).
